application: vladis4661
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:      #If someone comes to a particular URL this is the thing that handles it
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /.*     
  script: main.application  


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest