# poker:
	# g++ hw3.cpp Main.cpp -o poker
# clean:
	# rm poker



 XXFLAGS = -std=c++0x
 OBJS = program.o maze.o
 SRCS = program.cpp maze.cpp
 HEADERS = maze.h

 pacman: ${SRCS} ${HEADERS}
			 ${CXX} ${CXXFLAGS} ${SRCS} -o pacman

 clean:
			 rm -f *.o pacman

