# poker:
	# g++ hw3.cpp Main.cpp -o poker
# clean:
	# rm poker



 XXFLAGS = -std=c++0x
 OBJS = hw3.o Main.o
 SRCS = hw3.cpp Main.cpp
 HEADERS = hw3.hpp

 poker: ${SRCS} ${HEADERS}
			 ${CXX} ${CXXFLAGS} ${SRCS} -o poker

 clean:
			 rm -f *.o poker

